import type { Metadata } from "next";
import { Syne, Bricolage_Grotesque } from "next/font/google";
import { cn } from "@/lib/utils";
import { Header, Footer, LenisProvider, ThemeProvider } from "@/components/ui";
import "./globals.css";

const syne = Syne({
	subsets: ["latin"],
	weight: "variable",
	preload: true,
	variable: "--font-syne",
});

const brico = Bricolage_Grotesque({
	preload: true,
	subsets: ["latin"],
	weight: "variable",
	variable: "--font-brico",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			<body
				className={cn(
					"min-h-screen antialiased overflow-x-clip",
					syne.variable,
					brico.variable
				)}
			>
				<LenisProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<Header />
						{children}
						<Footer />
					</ThemeProvider>
				</LenisProvider>
			</body>
		</html>
	);
}
